const express = require("express");
const Router = express.Router();
const authController = require("../controller/authController");
Router.post("/signUp", authController.signUp);
Router.post("/login", authController.login);
Router.post("/forgotPassword", authController.forgotPassword);
Router.patch("/resetPassword/:token", authController.resetPassword);
Router.use(authController.protect);
Router.patch("/updatePassword", authController.updatePassword);
// Router.patch("/updateMe", userController.updateMe);
module.exports = Router;
